#+AUTHOR: Perry Smith
#+EMAIL:  pedz@easesoftware.com

* AF Selection                                                       :always:

First, the call_menu(item="AF area selection control") item can
be set to either [[file:svg/icon_Button_M_Fn_w60.svg]]
{{{menu-setting(M-Fn)}}} or [[file:svg/icon_dial_bk.svg]]
{{{menu-setting(Main Dial)}}}.  When set to {{{m-fn}}},
when a button set to the {{{function(AF point selection)}}}
function is pushed (and it may be released), each push of the
{{{menu-setting(M-Fn)}}} button will cycle through the AF areas that
have been enabled in the call_menu(item="Limit AF areas").
When call_menu(item="AF area selection control") item is set to
the {{{main-dial}}}, then turning the Main dial selects
the AF area.

During the time that {{{function(AF point selection)}}} is active, the
{{{info-button}}} may be pressed when one of the areas
that do not have the lock icon is selected to change the state of the
call_menu(item="Whole area tracking Servo AF").

When [[file:svg/icon_AF-area_flexible-zone1.svg]],
[[file:svg/icon_AF-area_flexible-zone2.svg]], or
[[file:svg/icon_AF-area_flexible-zone3.svg]] is selected, the
[[file:svg/icon_rate.svg]] button may be pushed at which point the
{{{main-dial}}} controls the horizontal size and the {{{qcd-1}}}
controls the vertical size.

The Multi-controller can be set to {{{function(Direct AF point
selection)}}} or it can be set to {{{function(Off)}}}.  When set to
{{{function(Direct AF point selection)}}}, moving the Multi-controller
in any of the eight directions at any time will move the AF area.
When the Multi-controller is set to {{{function(Off)}}}, then under
normal conditions, the Multi-controller does nothing.  After the
{{{function(AF point selection)}}} button is pressed, the
Multi-controller can be used to move the AF area.  This is also true
when the call_menu(item="AF area selection control") item is
set to [[file:svg/icon_dial_bk.svg]] the {{{menu-setting(Main Dial)}}}.

After the {{{function(AF point selection)}}} button is pressed, the AF
area may also be moved vertically with the {{{qcd-1}}} and
horizontally with the {{{main-dial}}} when the call_menu(item="AF area
selection control") item is set to
[[file:svg/icon_Button_M_Fn_w60.svg]] {{{menu-setting(M-Fn)}}}.
