#+AUTHOR: Perry Smith
#+EMAIL:  pedz@easesoftware.com
#+MACRO: af-operation-menu call_menu(item="AF operation")
#+MACRO: ai-focus-button On the R5 Mark II, this button has no effect when {{{af-operation-menu}}} is set to {{{menu-setting(AI Focus)}}}.
#+MACRO: when-pressed When a button assigned to this function is pressed
#+MACRO: when-held-down When a button assigned to this function is held down

* Functions available for customization {{{model}}}                  :always:

Currently this is just the list of icons and brief descriptions for
each of the functions that can be assigned on single buttons on the
{{{model}}}.  My hope is to add decent descriptions to some / most /
all??? of these over time.

Mild disclaimer: I own an R5 Mk II and an R1.  Generally I am fumbling
with the R5 Mk II except when I happen to notice a difference.

#+BEGIN_COMMENT
I intend to come back finish this and include it ...

There are edge cases that I have discovered which no one probably
cares about but I will describe them here.  [[When an AF area with the lock icon is selected][When an AF area with the
lock icon is selected]] the call_menu(item="Subject to detect ")
is disabled.  But the camera appears to still remember the last
setting for when [[file:svg/icon_Tracking_select_afon.svg]]: AF on
detected subject
#+END_COMMENT

  * [[file:svg/icon_metering-af-start.svg]]: Metering and AF start ::
    One of the four options shutter button half press is able to do.
    When the shutter button is half pressed, AE metering and AF are
    both started and continue until the button is either released or
    fully depressed which takes a photo.  If the button is released,
    AE continues for another eight seconds but AF stops.

  * [[file:svg/icon_af-off.svg]]: AF stop ::
    When a button is held down that starts AF, focus will be
    re-achieved as the situation changes.  But if a button set to AF
    stop is also held down, focusing will stop (as the name
    implies). This makes the most sense if the shutter button half
    press is set to one of the two settings that has AF start although
    there may be other situations as well.

  * [[file:svg/icon_af-frame-button.svg]]: AF point selection ::
    The *AF point selection* function is described in [[AF
    Selection][AF Selection]].

  * [[file:svg/icon_direct_af-point.svg]]: Direct AF point selection ::
    This can only be set on the Multi-controller.  When set this way,
    the eight way movements move the AF area in the direction the
    controller is moved.

  :r1-only:
  * [[file:svg/icon_AF_frame_direct_metering.svg]]: Direct AF pt sel (during meter) ::
    This is can only be set on the [[file:svg/icon_af-on.svg]] AF start
    button/Smart controller.  When a button set to any of the metering
    start functions is pressed and for eight seconds after it has been
    released, the AF area can be moved via finger movement across the
    [[file:svg/icon_af-on.svg]] AF start button/Smart controller.
  :end:

  * [[file:svg/icon_point_to_center.svg]]: Set AF point to center ::
    Pressing a button assigned to this function will move the AF area
    to the center.

  * [[file:svg/icon_AF_tracking_start.svg]]: Start/stop whole area AF tracking ::
    This setting is detailed in the [[AF Focusing][AF Focusing]] section.

  * [[file:svg/icon_switch-af-point.svg]]: Switch to registered AF point ::
    This feature is fairly well documented in the manual.  It is
    documented [[https://cam.start.canon/en/C018/manual/html/UG-04_AF-Drive_0060.html][here]] for the R1 and [[https://cam.start.canon/en/C017/manual/html/UG-04_AF-Drive_0060.html][here]] for the R5 Mark II.

  * [[file:svg/icon_switch-af-func.svg]]: Switch to registered AF func. ::
    This function allows a single button to be configured to set up
    many of the AF settings via the {{{info-button}}}.
    The settings include:
    * AF area
    * Whole area tracking Servo AF
    * Subject to detect
    * Spot detection
    * Eye detection
    * Servo AF characteristics
    * Case Auto character.
    * Tracking sensitivity
    * Accel./decel. tracking
    * Servo 1st image priority
    Each of these can be enabled making the specified setting take
    effect or not leaving the specified setting unchanged.

  * [[file:svg/icon_direct_af-area.svg]]: Direct AF area selection ::
    Each push of the button assigned to this function cycles through
    the AF areas that are enabled via the
    call_menu(item="Limit AF areas").

  * [[file:svg/icon_Subject_tracking_direct_select.svg]]: Direct select of sub to detect ::
    Each push of the button assigned to this function cycles through
    the subject types that are enabled via the
    call_menu(item="Limit subject to detect").  [fn:: The
    call_menu(item="AF area") can not have a lock icon because
    these areas disable call_menu(item="Subject to detect").]
    ????

  * [[file:svg/icon_oneshot-servo.svg]]: One-Shot AF *[[file:svg/icon_arrows-left-right.svg]] Servo AF ::
    The call_menu(item="AF operation") cycles from One-Shot AF
    to Servo AF with each push of the button assigned to this
    function. {{{include-if(R5MkII, {{{ai-focus-button}}})}}}

  * [[file:svg/icon_Metering_Afstart_GAZEconfirm.svg]]: Moving AF pt, meter., AF by eye ctrl ::
    One of the four options shutter button half press is able to do.
    call_menu(item="Eye control") must be on.  When the shutter
    button is half pressed, AE metering and AF with eye control are
    both started and continue until the button is either released or
    fully depressed which takes a photo.  If the button is released,
    AE continues for another eight seconds but AF stops.  The AF area
    is moved to where the eye control is at the moment the shutter
    button is half pressed.  Keeping it half pressed does not allow
    the AF area to move around with the eye.  When Eye control is off,
    this setting appears to work the same as Metering and AF start.

  * [[file:svg/icon_Nac2_confirm.svg]]: Move AF point by eye control ::
    call_menu(item="Eye control") must be on.  At the moment
    the button is pressed, the AF area is moved to where the eye
    control pointer is.  Neither AF nor AE are started.

  * [[file:svg/icon_Nac2_confirm_and_AF.svg]]: Moving AF point, start AF by eye ctrl ::
    call_menu(item="Eye control") must be on.  At the moment
    the button is pressed, the AF area is moved to where the eye
    control pointer is.  Both AE and AF are started and continue while
    the button is held down.  AE continues for eight seconds after the
    button is released.

  * [[file:svg/icon_Nac2_function.svg]]: Eye control ::
    Eye control is toggled on and off with each push of the button.
    This is the same setting as the
    call_menu(item="Eye control").

  * [[file:svg/icon_Tracking_select_afon.svg]]: AF on detected subject ::
    {{{when-pressed}}},
    call_menu(item="AF area") is temporarily set to
    {{{menu-setting(Whole area AF)}}} and the auto focus system is
    engaged.

  * [[file:svg/icon_eyes_af.svg]]: Eye Detection AF ::
    {{{when-pressed}}},
    call_menu(item="AF area") is temporarily set to
    {{{menu-setting(Whole area AF)}}},
    call_menu(item="Eye detection") is enabled.  It isn't clear if
    {{{menu-setting(Auto)}}}, {{{menu-setting(Right Eye)}}}, or
    {{{menu-setting(Left Eye)}}} is selected.  And the auto focus
    system is engaged.

  * [[file:svg/icon_Eye_detection_direct_select.svg]]: Eye detection ::
    Each push of this button cycles through the Off, Auto, L Eye, and
    R Eye options enabled in the call_menu(item="L/R eye
    detection").

  * [[file:svg/icon_Subject_spot_detection.svg]]: Spot detection ::
    Cycles ~Spot detection~ off and on with each push of the button
    when call_menu(item="Subject to detect") is set to
    {{{menu-setting(Vehicles)}}}.  ~Spot detection~ is normally
    altered with the {{{info-button}}} when
    {{{menu-setting(Vehicles)}}} is selected for
    call_menu(item="Subject to detect").

  * [[file:svg/icon_Personal_authentication.svg]]: Register people priority ::
    The call_menu(item="Register people priority") is
    {{{menu-setting(Enabled)}}} and {{{menu-setting(Disabled)}}} with
    each push of the button assigned to this function.

  * [[file:svg/icon_Action_detect.svg]]: Action Priority ::
    The call_menu(item="Action Priority") is
    {{{menu-setting(Enabled)}}} and {{{menu-setting(Disabled)}}} with
    each push of the button assigned to this function.  Funny note:
    When setting this option via the menu, the choices are
    {{{menu-setting(Enable)}}} and {{{menu-setting(Disable)}}} but
    when changing it via the button, the settings are
    {{{menu-setting(Off)}}} and {{{menu-setting(On)}}}.  But for
    {{{function(Register people priority)}}}, it is just the opposite.

  * [[file:svg/icon_Af_mf_switch.svg]]: Focus mode ::
    I don't have a lens to test this with but I presume that it mimics
    call_menu(item="Focus mode") with each push of the button
    assigned to this function cycling between manual focus and auto
    focus modes.

  * [[file:svg/icon_mf-peaking-set.svg]]: Peaking ::
    When the camera is set to manual focus, [fn:manual-focus: The
    camera is put into manual focus mode via the MF/AF switch on the
    lens or call_menu(item="Focus mode")] then the
    call_menu(item="MF peaking settings") has an affect.
    {{{when-pressed}}}, it will toggle the top sub-option, ~Peaking~,
    of that menu {{{menu-setting(On)}}} and {{{menu-setting(Off)}}}.

  * [[file:svg/icon_focus-guide.svg]]: Focus guide ::
    When the camera is set to manual focus,[fn:manual-focus] then the
    call_menu(item="Focus guide") has an effect.  A button
    assigned to this function will turn that setting
    {{{menu-setting(On)}}} and {{{menu-setting(Off)}}} with each push
    of the button.

  * [[file:svg/icon_Focus_preset_register.svg]]: Register focus preset ::
    The manual has a good description of this function along with
    {{{function(Recall focus preset)}}}.  When the button assigned to
    this is pushed, the current focal distance is recorded.  This will
    persist across shooting mode changes and even power cycles but not
    lens changes.

  * [[file:svg/icon_Focus_preset_call.svg]]: Recall focus preset ::
    The manual has a good description of this function along with
    {{{function(Register focus preset)}}}.  When the button assigned
    to this function is pushed, the preset focal distance is recalled.
    After a lens change, there appears to be something that is set as
    a default but it isn't the value recorded.

  * [[file:svg/icon_Face_only_direct_select.svg]]: Subj. detect. AF ::
    {{{when-pressed}}}, subject detect is enabled along with
    call_menu(item="Whole area tracking Servo AF").  What isn't clear
    is which type of subjects will be detected.

  * [[file:svg/icon_continuous-shooting.svg]]: Drive mode ::
    {{{include-if(R5MkII, Selects the next drive mode with each push
    of the button assigned to this function.)}}}  {{{include-if(R1,
    Selects the next drive mode with each push of the button assigned
    to this function which has been enabled in
    call_menu(item="Restrict drive modes").)}}}

  * [[file:svg/icon_Drive_mode_change.svg]]: Switch *[[file:svg/icon_Electric_Shutter.svg]] cont. shooting modes ::
    When electronic shutter is being used and the drive mode is one of
    the continuous shooting speeds, holding down a button assigned to
    this function can select a different continuous shooting speed.
    The continuous shoot speed while the button is not held down is
    selected by various ways including call_menu(item="Drive
    mode"). The continuous shooting speed selected while the button is
    held down is selected via the {{{info-button}}} while selecting
    this function.

  * [[file:svg/icon_ae-lock-af-stop.svg]]: AE lock, AF stop ::
    As the name implies, this appears to lock the auto exposure and
    stop the auto focus engine.

  * [[file:svg/icon_metering-evaluative.svg]]: Metering start ::
    One of the four options the shutter button half press is able to
    do.  When the shutter button is half pressed (and held that way),
    metering starts and continues until the button is fully released
    or fully depressed.  When the button is released, AE continues for
    another eight seconds.

  * [[file:svg/icon_ae-lock.svg]]: AE lock ::
    When the button assigned to this function is pushed, the exposure
    is locked.  It will remain locked as long as the button is held
    down and for the value set in call_menu(item="Metering timer")
    after release.

  * [[file:svg/icon_ae-lock-hold.svg]]: AE lock (hold) ::
    This function cycles between holding and releasing the exposure
    lock.  The first press (and release) will hold the current
    exposure settings in what appears to be an indefinite time.  The
    second press will release the hold and let the auto exposure
    reevaluate.

  * [[file:svg/icon_ae-lock.svg]]: AE lock (while button pressed) ::
    One of the four options shutter button half press is able to do.
    The best way to think of this "metering start and AE lock".  When
    any button with "metering start" is momentarily pressed, it starts
    an eight second timer where the AE engine is running.  After eight
    seconds, it stops.  When the shutter button half press function is
    set to AE lock (while button pressed), touching the shutter button
    starts AE.  Holding the shutter half pressed (as well as taking
    the image) will cause AE to lock.

  * [[file:svg/icon_ael-fel.svg]]: AE lock/FE lock ::
    Sorry... I don't want to muck about with flash right now.  Maybe
    later.

  * [[file:svg/icon_AE_lock_OFF.svg]]: Release AE Lock ::
    {{{when-pressed}}} and released,
    any exposure lock is released.

  * [[file:svg/icon_func-exp.svg]]: Expo comp (hold btn, turn *[[file:svg/icon_dial_bk.svg]]) ::
    In P, Tv, Av, and M shooting modes, holding a button assigned to
    this function down enables the {{{main-dial}}} to adjust the exposure
    compensation.  In Fv mode however, even after releasing the
    button, the main dial continues to adjust the exposure
    compensation until the call_menu(item="Metering timer") expires.

  * [[file:svg/icon_iso.svg]]: ISO speed ::
    {{{when-pressed}}} and released, a
    display showing the ISO and any of the dials will adjust the
    value.

  * [[file:svg/icon_func-set-iso.svg]]: Set ISO speed(hold btn,turn*[[file:svg/icon_dial_bk.svg]]) ::
    {{{when-pressed}}} and held, the
    {{{main-dial}}} is used to adjust the ISO.

  * [[file:svg/icon_flash.svg]]: Flash firing ::
    Sorry... I don't want to muck about with flash right now.  Maybe
    later.

  * [[file:svg/icon_fe-lock2.svg]]: FE lock ::
    Sorry... I don't want to muck about with flash right now.  Maybe
    later.

  * [[file:svg/icon_image-size.svg]]: Image size selection ::
    Not documented [fn:none: Many functions, like this one, I have no interest in.  For me, I pick
    to record in RAW or CRAW and quickly changing image sizes seems
    like an absurd waste of a button.  If you really would like these
    documented, please make a request.  I may get to them eventually anyway.]

  * [[file:svg/icon_one-touch-img-quality.svg]]: One-touch image quality setting ::
    Not documented [fn:none]

  * [[file:svg/icon_one-touch-img-quality-h.svg]]: One-touch image quality (hold) ::
    Not documented [fn:none]

  * [[file:svg/icon_change-aspect.svg]]: *[[file:svg/icon_still.svg]]Cropping/aspect ratio ::
    When the button assigned to this function is pressed (and can be
    released or not), a horizontal menu appears in the screen and any
    of the dials can be used to select the desired crop and aspect
    ratio.

  * [[file:svg/icon_swich-aspect.svg]]: Switch between crop/aspect ::
    During selecting this function, the {{{info-button}}} is used to
    check or uncheck the which cropping and aspect ratios to be made
    available.  The full selection is full, 1.6 crop, 4:3 aspect
    ration and 16:9 aspect ratio.
    
    When the button assigned to this function is pressed the next
    selection in the set just described is chosen.

  * [[file:svg/icon_raw-auto-light-opt.svg]]: Auto Lighting Optimizer ::
    {{{when-pressed}}}, a horizontal
    menu is displayed and matches the function of the
    call_menu(item="Auto Lighting Optimizer") with the
    {{{info-button}}} enabling or disabling the optimizer from working
    with the *[M]* and *[BULB]* shooting modes.  Any dial can be used
    to select between the different optimizer options.

  * [[file:svg/icon_wb.svg]]: White balance selection ::
    {{{when-pressed}}}, a horizontal
    menu appears with the various preset values of white balance such
    as cloudy, sunny, etc.  Any of the dials can be used to select the
    desired setting.  The {{{info-button}}} can be pressed which
    presents an X-Y view of the white balance where the setting can be
    moved by the Multi-Controller.  The {{{main-dial}}} can be used to set
    the white balance bracketing.

  * [[file:svg/icon_Wb_shift.svg]]: WB Shift/Bkt. ::
    This is available only in still photo shooting.  {{{when-pressed}}}, a X-Y
    view of the white balance is presented and the multi-controller
    can be used to adjust the settings.  The {{{main-dial}}} can be
    used to adjust the white balance bracketing.

  * [[file:svg/icon_Wb_shift.svg]]: WB correction ::
    This is available only in moving shooting.  {{{when-pressed}}}, a X-Y view
    of the white balance is presented and the multi-controller can be
    used to adjust the settings.  The adjustment for bracketing isn't
    present since bracketing during moving shooting isn't possible.

  * [[file:svg/icon_func-picstyle.svg]]: Picture Style ::
    There are eleven Picture Styles defined.  {{{when-pressed}}}, a
    menu of these eleven styles is displayed as two lines with the top
    line having six selections and the second line having five.  The
    multi-controller may be used in both the horizontal and vertical
    motions to select one of the styles.  Any of the dials may also be
    used to select one of the styles.  Also, the {{{info-button}}}
    brings up a different screen with the six attributes of the
    selected style before the {{{info-button}}} was pressed are
    available in a vertical menu.  The {{{qcd-1}}} is used to select
    which attribute to change while the {{{main-dial}}} is used to
    change its value.

  * [[file:svg/icon_record-func-card-sel.svg]]: Record func+card/folder sel. ::
    {{{when-pressed}}}, a menu
    identical to the call_menu(item="Record func+card/folder sel.") is
    presented with the same functionality.

  * [[file:svg/icon_False_Color.svg]]: False color ::
    Only available for Movie Shooting.  With each push of a button
    assigned to this function is pressed, the ~False color~ sub-option
    of the call_menu(item="False color set.") is toggled on and off.

  * [[file:svg/icon_zebra_select.svg]]: Zebra ::
    Only available for Movie Shooting.    With each push of a button
    assigned to this function is pressed, the ~Zebra~ sub-option
    of the call_menu(item="False color set.") is toggled on and off.

  * [[file:svg/icon_mov.svg]]: Movie recording ::
    Only available for Still Photo Shooting.  This is the default
    function for the Movie shooting button.  {{{when-pressed}}}, the
    camera switches into [{{{c3-movie}}}] and starts recording.  A
    subsequent push will stop the recording.

  * [[file:svg/icon_pause-mov-servo.svg]]: Pause Movie Servo AF ::
    Only available during Movie Shooting.  The ~Movie Servo AF~
    sub-option of the call_menu(item="Movie Servo AF") must be set to
    {{{menu-setting(Enable)}}} for this function to do anything.
    While Movie Shooting, pressing a button assigned to this function
    once will {{{menu-setting(Disable)}}} the ~Movie Server AF~.
    Pressing the button again will {{{menu-setting(Enable)}}} ~Movie
    Server AF~.  The function is *not* sticky.

  * [[file:svg/icon_Audio_status.svg]]: Audio Status ::
    Only available during Movie Shooting.  By default, this function
    is assigned to the Depth-of-field preview button.
    {{{when-pressed}}}, an Audio Status display is brought up
    identical to call_menu(item="Audio Status").

  * [[file:svg/icon_Powerzoom_Tele.svg]]: Cinema zoom (to tele) ::
    I don't have a lens to test this function out.
    
  * [[file:svg/icon_Powerzoom_Wide.svg]]: Cinema zoom (to wide) ::
    I don't have a lens to test this function out.

  * [[file:svg/icon_Custum_picture.svg]]: Custom Picture ::
    Only available during Movie Shooting.  {{{when-pressed}}}, the
    call_menu(item="Custom Picture") menu is brought up.

  * [[file:svg/icon_PreRecording_setting.svg]]: Pre-recording ::
    Only available during Movie Shooting.  {{{when-pressed}, the
    ~Pre-recording~ sub-option of the call_menu(item="Pre-recording
    set.") is toggled.  This function is sticky.

  * [[file:svg/icon_Self_timer.svg]]: Movie self-timer ::
    Only available during Movie Shooting.  {{{when-pressed}}}, a
    horizontal menu is presented with the three options presented by
    call_menu(item="Movie self-timer"): {{{menu-setting(Off)}}},
    {{{menu-setting(10 sec)}}}, and {{{menu-setting(2 sec)}}}.  Any
    dial as well as the Multi-controller can be used to select the
    desired setting.

  * [[file:svg/icon_Relax_temp_rise_setting_on.svg]]: Standby: Low res. ::
    Only available during Movie Shooting.  {{{when-pressed}}}, the
    call_menu(item="Standby; Low res.")  is toggled.  This function is
    sticky.

  * [[file:svg/icon_flash-func-settings.svg]]: Flash function settings ::
    Sorry... I don't want to muck about with flash right now.  Maybe
    later.

  * [[file:svg/icon_External_flash_Gr.svg]]: Quick flash group control ::
    Sorry... I don't want to muck about with flash right now.  Maybe
    later.

  * [[file:svg/icon_func-dial.svg]]: Dial function settings ::
    {{{when-pressed}}}, a grid of up to ten functions is displayed.
    The grid can be one or two lines tall and up to five columns
    across with one of the columns being selected.  If the function is
    assigned to the {{{m-fn}}} button, then the {{{m-fn}}} icon is
    displayed on the left meaning that subsequent pushes of that
    button will move the selected column to the right and then wrap
    around to the first column.  If the {{{m-fn}}} is not assigned to
    this function, then the {{{qcd-2}}} icon is displayed on the left.
    In all cases, the {{{qcd-2}}} can be used to select the desired
    column as well as the button(s) that the function has been
    assigned to.

    Once a column has been selected by subsequent pressing of the
    button or by the {{{qcd-2}}}, the values of the selected function
    on the top row can be adjusted by the {{{main-dial}}} while the
    values of the selected function on the bottom row can be adjusted
    by the {{{qcd-1}}}.  There are icons presented so all this doesn't
    need to be memorized.

    While selecting this function for a particular button, the
    {{{info-button}}} can be pressed to configure the grid of ten
    possible positions.  The available functions are:
    * ISO speed
    * Drive mode
    * AF operation
    * White balance
    * Flash exp. comp
    * Exposure compensation
    * AF area
    * Metering mode
    * Picture Style
    * Off

  :r1-only:
  * [[file:svg/icon_cycle-set-func.svg]]: Cycle between the set functions ::
    Pressing a button assigned to this function will display an
    attribute to be adjusted.  Subsequent pushes will bring up the
    next attribute that has been enabled.  The seven attributes or
    attribute pairs are listed below.  They are enabled via the
    {{{info-button}}} during the process of assigning this function to
    a button.
    * ISO speed
    * Exposure compensation
    * White balance
    * Drive mode / AF operation
    * Flash exp. comp / Metering mode
    * AEB setting
    * Shooting mode
  :end:

  * [[file:svg/icon_func-brightness.svg]]: Maximize screen brightness (temp) ::
    {{{when-pressed}}} (and released),
    the back LCD screen will go to maximum brightness.  A subsequent
    push will restore the screen's brightness to it regular setting.
    No change to the EVF that I can see.

  * [[file:svg/icon_power_off.svg]]: Power off ::
    {{{when-pressed}}}, the camera goes to sleep however the shutter
    does not close.

  * [[file:svg/icon_func-display-off.svg]]: Screen off ::
    {{{when-pressed}}}, the rear LCD display is turned off.

  * [[file:svg/icon_unlock-btn-pressed.svg]]: Unlock while button pressed ::
    If the Power/multi-function lock switch is in the lock position,
    then when a button assigned to this function is held down, the
    controls become unlocked and the camera behaves as if the
    Power/multi-function lock switch is in the On position.  This
    function can only be assigned to the DOF button and the button
    that some lenses have.

  * [[file:svg/icon_btn-illum-panel-info.svg]]: Short press: LCD illumination - Long press: LCD info switching ::
    This can only be assigned to the {{{lcd-button}}}.  As the name
    implies, a short press will turn the top LCD illumination on and
    another short press will turn it off.  Long presses will cycle
    through the two screens of information.

  * [[file:svg/icon_btn-panel-illum-info.svg]]: Short press: LCD info switching - Long press: LCD illumination ::
    This can only be assigned to the {{{lcd-button}}} and is its
    default assignment.  As the name implies, a long press will turn
    the top LCD illumination on and another long press will turn it
    off.  Short presses will cycle through the two screens of
    information.

  * [[file:svg/icon_panel-illum.svg]]: LCD panel illumination ::
    {{{when-pressed}}}, the illumination of the top LCD panel is turned on and
    then off with a subsequent push.

  * [[file:svg/icon_btn-panel-illum-info2.svg]]: LCD panel info switching ::
    {{{when-pressed}}}, the information displayed on the top LCD panel cycled.


  * [[file:svg/icon_mode.svg]]: Shooting mode settings ::
    This is the default for the {{{mode-button}}}.
    {{{when-pressed}}}, a two line by five element grid of all the
    possible modes is displayed.  Those that have been enabled in the
    call_menu(item="Restrict shooting modes") are highlighted.  Any of
    the dials as well as the Multi-controller can be used to select
    the desired mode.  Unlike some functions, the {{{set-button}}}
    does not have to be pressed for the change to take affect.
    e.g. the shutter button can be half pressed and the camera will
    still make the assignment.

  * [[file:svg/icon_mode-c.svg]]: Switch to Custom shooting mode ::
    Okay, to me this is a little weird.  {{{when-pressed}}}, the
    camera will cycle through the custom modes that have been enabled
    in the call_menu(item="Restrict shooting modes").  In addition, it
    will also select whatever was last selected via the
    {{{function(Shooting mode settings)}}} described above.  For
    example, if C1-C3 are enabled and the last mode switched to by the
    {{{mode-button}}} is Av.  Then pushing this button will cycle
    through the C-C3 modes as well as the Av mode but not the other
    enabled modes.

  * [[file:svg/icon_silent.svg]]: Silent shutter function ::
    {{{when-pressed}}}, the setting of call_menu(item="Silent shutter
    function") is toggled.

  * [[file:svg/icon_Focus_control_switch.svg]]: Switch focus/control ring ::
    Testing on the R5 Mark II with firmware 1.3.1 (June 2026) and the
    Canon RF 70-200mm f/2.8 L IS USM Z Lens, the
    call_menu(item="Focus/control ring") menu appears.  The lens has
    both a control and a focus ring.  Just as is described in the
    "Lenses for which this menu is displayed that have both focusing
    and control rings" section of the [[https://cam.start.canon/en/C017/manual/html/UG-08_Customize_0030.html][Control Customization Details]] of
    the R5 Mark II manual, in one option, the focus and control rings
    function as normal and in the other option, the control ring is
    disable and the focus ring acts as the control ring.
    {{{when-pressed}}}, the option just describe toggles between the
    two settings.  It is sticky.  I do not have a lens with just one
    ring and no switch so I can't test the "Lenses without a
    focusing/control ring switch" condition.

    I do have lenses with just one ring but they have a switch.  This
    function appears to do nothing.  I also have the Canon RF 35mm
    f/1.8 Macro IS STM Lens in which case the menu item does not
    appear and this function appears to do nothing as well.

  * [[file:svg/icon_func-depth.svg]]: Depth-of-field preview ::
    This is the default function assigned to the Depth-of-field
    preview button.  When the call_menu(item="Display simulation") is
    set to {{{menu-setting("Exposure+DOF")}}}, this function does
    nothing because the camera is already adjusting the display
    simulation for exposure as well as depth of field.
    {{{when-pressed}}} and call_menu(item="Display simulation") is set
    for any of the other three options, the aperture is closed to the
    value selected so the user can judge the depth of field that will
    result when the photograph is taken.

  * [[file:svg/icon_func-reset1.svg]]: Reset selected item in Fv mode ::
    {{{when-pressed}}} and the camera is in Fv mode or a custom mode
    based upon Fv mode, the selected item that has been selected via
    the {{{qcd-2}}} will be reset to Auto.

  * [[file:svg/icon_func-reset2.svg]]: Reset Tv/Av/[[file:svg/icon_exp-com.svg]]/ISO in Fv mode ::
    {{{when-pressed}}} and the camera is in Fv mode or a custom mode
    based upon Fv mode, all of Tv/Av/[[file:svg/icon_exp-com.svg]]/ISO are
    reset to Auto.

  * [[file:svg/icon_btn_quick.svg]]: Quick Control screen ::
    {{{when-pressed}}}, the Quick Control screen is presented just as
    if the {{{quick-control-button}}} had been pushed.

  * [[file:svg/icon_magnify.svg]]: Magnify/Reduce ::
    {{{when-pressed}}}, the Quick Control screen is presented just as
    if the {{{magnify-button}}} had been pushed.

  * [[file:svg/icon_playback.svg]]: Image replay ::
    {{{when-pressed}}}, the Quick Control screen is presented just as
    if the {{{playback-button}}} had been pushed.  There is one subtle
    difference.  When the actual {{{playback-button}}} is pressed a
    second time, the camera goes back to shooting mode but this
    doesn't appear to happen with a button assigned to this function.

  * [[file:svg/icon_play_magnified.svg]]: Magnify images during playback ::
    {{{when-pressed}}}, it has the same effect as if the
    {{{playback-button}}} had been pressed followed by the
    {{{magnify-button}}}.  Subsequent presses toggles the
    magnification on and off.

  * [[file:svg/icon_regi-recall-func.svg]]: Register/recall shooting func ::
    Perhaps the single most universal function.  Before I get into the
    details, here are some subtleties that I have found.  *Yes*, this
    function can be assigned to more than one button but *No* each
    button will have the same settings. ☹️

    When the {{{info-button}}} is pressed while assigning this
    function to a button, the user shown a list of nineteen
    attributes.  The list has two columns.  The left column is a check
    box.  When checked, then this attribute will be applied to the
    camera while the assigned button is being pressed.  The right
    column are the values that the attribute can be assigned.  For
    example, Shutter speed can be assigned any value from 30" to
    1/32000.  Curiously, Auto is not in the list.

    Here are the list of attributes that can be set.  Have FUN!!!
    * Shooting mode
    * Shutter speed
    * Aperture
    * ISO speed
    * Metering mode
    * Exposure compensation
    * White balance
    * AF area
    * Whoe area tracking Server AF
    * Subject to detect
    * Spot detection
    * Eye detection
    * Servo AF characteristics
    * Case Auto character.
    * Tracking sensitifity
    * Accel./decel. tracking
    * Servo 1st image priority
    * AF start position
    * AF operation

  * [[file:svg/icon_menu.svg]]: Menu display ::
    {{{when-pressed}}}, the menu appears just as if the
    {{{menu-button}}} had been pressed.

  * [[file:svg/icon_Tv_step.svg]]: Manual HF anti-flicker shoot(Tv) ::
    I don't feel like I 100% understand the anti-flicker abilities and
    I don't have flickering lights at home to test with.

  * [[file:svg/icon_Tv_recommendation.svg]]: Recom. Tv for HF anti-flicker shoot ::
    I don't feel like I 100% understand the anti-flicker abilities and
    I don't have flickering lights at home to test with.

  * [[file:svg/icon_ts-enable.svg]]: Touch Shutter ::
    {{{when-pressed}}}, the call_menu(item="Touch Shutter") setting is
    toggled.

  * [[file:svg/icon_OVF_View_Assist.svg]]: OVF sim. view assist ::
    {{{when-pressed}}}, the call_menu(item="OVF sim. view assist")
    setting is toggled.

  * [[file:svg/icon_View_fps.svg]]: *[[file:svg/icon_display_slash_finder.svg]] Display frame rate set. ::
    {{{when-pressed}}}, the call_menu(item="Display frame rate set.")
    is toggled between {{{menu-setting(Power Saving)}}} and
    {{{menu-setting(Smooth)}}}.

  * [[file:svg/icon_data-transfer.svg]]: Communication function ::
    {{{when-pressed}}}, a menu essentially the same as Tab 2 of the
    {{{comm-menu}}} is presented.  The functions in the list are:
    * Transfer images to FTP server
    * Connect to EOS Utility
    * Upload to image.canon
    * Sync time between cameras
    * Connect to smartphone(tablet)
    * Connect to Wireless remote

    There is also a "Connection settings" button that brings up the
    list of Connection settings: the same menu that is presented when
    the ~Connection settings~ sub-option of the
    call_menu(item="Network settings") is selected.

  * [[file:svg/icon_airplane_mode.svg]]: Airplane mode ::
    {{{when-pressed}}}, a menu is presented for Airplane mode.  The
    user can select {{{menu-setting(On)}}} or {{{menu-setting(Off)}}}.

  * [[file:svg/icon_new-folder.svg]]: Create folder ::
    8
    
  * [[file:svg/icon_func-switch-vf-screen.svg]]: Switch between VF/screen ::
    7

  :r1-only:
  * [[file:svg/icon_btn-magnify.svg]]: Magnify/Reduce button ::
    6

  * [[file:svg/icon_btn-playback.svg]]: Playback button ::
    5

  * [[file:svg/icon_info_monitor.svg]]: Info button ::
    4

  * [[file:svg/icon_btn-erase.svg]]: Erase button ::
    3

  * [[file:svg/icon_rate_monitor.svg]]: Rating button ::
    2
  :end:

  * [[file:svg/icon_le-mf-d.svg]]: No function (disabled) ::
    1
