#+TITLE:  Canon EOS Documentation Project
#+AUTHOR: Perry Smith
#+EMAIL:  pedz@easesoftware.com

To me, there are many subtle questions about how the Canon EOS cameras
work that are not answered in the manual.  The top most of these are
all the functions that can be assigned to buttons.  Most are not
documented at all.  This project is to document those areas that need
more documentation.

The project is hosted at [[https://github.com/pedz/Canon-EOS-Documentation-Project][Canon-EOS-Documentation-Project]].  If you
would like to help, please open a discussion in the project on GitHub.

The *Canon EOS R1 Menu.txt* and *Canon EOS R5 Mark II Menu.txt* are
UTF-8 files intended to be downloaded and stored on your phone.  Then
accessed and searched for the menu that you are looking for.  It will
provide you with info on where to find it on your camera.

 1. [[file:Canon EOS R1 Supplement.html][Canon EOS R1 Supplement]]
 2. [[file:Canon EOS R1 Menu.txt][Canon EOS R1 Menu.txt]] (right click and download)
 3. [[file:Canon EOS R5 Mark II Supplement.html][Canon EOS R5 Mark II Supplement]]
 4. [[file:Canon EOS R5 Mark II Menu.txt][Canon EOS R5 Mark II Menu.txt]] (right click and download)
